ALTER TABLE HJ_INFORMATION  MODIFY (HELPADDR VARCHAR2(200 BYTE) );

  CREATE TABLE "CCS"."APP_RECEIVER" 
   (	"PID" VARCHAR2(32 BYTE) NOT NULL ENABLE, 
	"HELPNAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"HELPMODE" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	"HELPTEL" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"HELPADDR" VARCHAR2(1024 BYTE) NOT NULL ENABLE, 
	"HELPCONTENT" VARCHAR2(1024 BYTE) NOT NULL ENABLE, 
	"HELPTYPE" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"HELPAREA" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"HELPGROUP" VARCHAR2(1 BYTE), 
	"STATUS" VARCHAR2(1 BYTE), 
	"IP" VARCHAR2(255 BYTE), 
	"CREATETIME" TIMESTAMP (6), 
	"DELETEFLAG" VARCHAR2(20 BYTE), 
	"UPDATEDT" TIMESTAMP (6), 
	"LASTHANDLER" VARCHAR2(32 BYTE), 
	 CONSTRAINT "APP_RECEIVER_PK" PRIMARY KEY ("PID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CCS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 0 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CCS" ;

  CREATE TABLE "CCS"."APP_RECEIVER_HIST" 
   (	"PID" VARCHAR2(32 BYTE) NOT NULL ENABLE, 
	"HELPNAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"HELPMODE" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	"HELPTEL" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"HELPADDR" VARCHAR2(1024 BYTE) NOT NULL ENABLE, 
	"HELPCONTENT" VARCHAR2(1024 BYTE) NOT NULL ENABLE, 
	"HELPTYPE" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"HELPAREA" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"HELPGROUP" VARCHAR2(1 BYTE), 
	"STATUS" VARCHAR2(1 BYTE), 
	"IP" VARCHAR2(255 BYTE), 
	"AGENTID" VARCHAR2(32 BYTE) NOT NULL ENABLE, 
	"CREATETIME" TIMESTAMP (6), 
	"DELETEFLAG" VARCHAR2(20 BYTE), 
	"UPDATEDT" TIMESTAMP (6), 
	"LASTHANDLER" VARCHAR2(32 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 0 PCTUSED 40 INITRANS 1 MAXTRANS 255 COMPRESS BASIC LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CCS" ;
 



  CREATE TABLE "CCS"."HJ_USERAPPINFO" 
   (	"PID" VARCHAR2(32 BYTE) NOT NULL ENABLE, 
	"USERID" VARCHAR2(32 BYTE) NOT NULL ENABLE, 
	"APPINFOID" VARCHAR2(32 BYTE) NOT NULL ENABLE, 
	"CREATETIME" TIMESTAMP (6), 
	"DELETEFLAG" VARCHAR2(1 BYTE), 
	"UPDATEDT" TIMESTAMP (6), 
	"LASTHANDLER" VARCHAR2(32 BYTE), 
	 CONSTRAINT "HJ_USERAPPINFO_PK" PRIMARY KEY ("PID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CCS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 0 PCTUSED 40 INITRANS 1 MAXTRANS 255 COMPRESS BASIC LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CCS" ;
 




  CREATE TABLE "CCS"."HJ_APPINFO" 
   (	"PID" VARCHAR2(32 BYTE) NOT NULL ENABLE, 
	"INFORMATIONID" VARCHAR2(32 BYTE) NOT NULL ENABLE, 
	"ORDERSMONEY" VARCHAR2(20 BYTE), 
	"ORDERSCOMMENTNUM" VARCHAR2(1 BYTE), 
	"ORDERSCOMMENTCONTENT" VARCHAR2(1024 BYTE), 
	"ORDERSSERVERSNAME" VARCHAR2(1024 BYTE), 
	"ORDERSERVERSPHONE" VARCHAR2(1024 BYTE), 
	"ORDERSERVERSSERVICETYPE" VARCHAR2(2048 BYTE), 
	"ORDERSSERVERSCHECK" VARCHAR2(2048 BYTE), 
	"ORDERSTYPE" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	"CREATETIME" TIMESTAMP (6), 
	"DELETEFLAG" VARCHAR2(20 BYTE), 
	"UPDATEDT" TIMESTAMP (6), 
	"LASTHANDLER" VARCHAR2(32 BYTE), 
	 CONSTRAINT "HJ_APPINFO_PK" PRIMARY KEY ("PID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CCS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 0 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CCS" ;
 

   COMMENT ON COLUMN "CCS"."HJ_APPINFO"."INFORMATIONID" IS '订单编号';
 
   COMMENT ON COLUMN "CCS"."HJ_APPINFO"."ORDERSMONEY" IS '订单金额';
 
   COMMENT ON COLUMN "CCS"."HJ_APPINFO"."ORDERSCOMMENTNUM" IS '服务评分:1 2 3 4 5 大于等于3满意 小于3不满意';
 
   COMMENT ON COLUMN "CCS"."HJ_APPINFO"."ORDERSCOMMENTCONTENT" IS '不满意原因，小于3才不为“”';
 
   COMMENT ON COLUMN "CCS"."HJ_APPINFO"."ORDERSSERVERSNAME" IS '服务者姓名';
 
   COMMENT ON COLUMN "CCS"."HJ_APPINFO"."ORDERSERVERSPHONE" IS '服务者联系方式';
 
   COMMENT ON COLUMN "CCS"."HJ_APPINFO"."ORDERSERVERSSERVICETYPE" IS '服务者服务内容';
 
   COMMENT ON COLUMN "CCS"."HJ_APPINFO"."ORDERSSERVERSCHECK" IS '保修评定内容';
 
   COMMENT ON COLUMN "CCS"."HJ_APPINFO"."ORDERSTYPE" IS '订单类型:1订单 2保修';
 

  CREATE UNIQUE INDEX "CCS"."HJ_APPINFO_INFOMATIONID" ON "CCS"."HJ_APPINFO" ("INFORMATIONID" DESC) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CCS" ;


#求助方式增加APP（编号6）